[workspace]
members = [
    "brass-aphid-wire-messages", 
    "brass-aphid-wire-record",
    "brass-aphid-wire-handshake", 
    "brass-aphid-wire-decryption",
    "brass-aphid-wire-macros",
    "brass-aphid-wire-messages/fuzz", 
    "capability-compendium", 
]

[workspace.package]
version = "0.0.3"
edition = "2021"
license = "Apache-2.0"
